### ISSUE TITLE
Issue on page /chapters/subtype-polymorphism.html

### ISSUE THREAD

**Issue by carldahlgren** [chrokh/the-oo-way#4]
Exercise 61.4

Can we send instances of ReverseCipher to encodeCharTwice? Why or why not?

Ska stå encodeStringTwice?

**Comment by chrokh** [comment]
Tackar för notisen. Menar faktiskt `encodeCharTwice`. Denna fråga handlar alltså om att reflektera över varför någonting inte fungerar. Men jag har slagit samman 61.4 med 61.3 så att de båda nu är 61.3 och förhoppningsvis förtydligat uppgiftsbeskrivningen. Tack igen!
