### ISSUE TITLE
Issue on page /chapters/abstract-injected-object-composition.html

### ISSUE THREAD

**Issue by nothxor** [chrokh/the-oo-way#5]
"In the chapter on [abstract injected object composition](https://theobjectorientedway.com/chapters/concrete-injected-object-composition.html#concrete-injected-object-composition-examples-general-flip-flop) we discussed how our flip flop cipher was coupled to"

Texten säger abstrakt, men länken säger konkret. :)

**Comment by chrokh** [comment]
Tack så mycket! Åtgärdat.
